services:
  service-discovery:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/key.json
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GIN_MODE=debug
    volumes:
      - /Users/jens/.config/gcloud/application_default_credentials.json:/srv/key.json
